# Generated by Django 4.1.7 on 2023-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_size',
            field=models.IntegerField(default=0),
        ),
    ]
