version: "3.9"
services:
  web:
    build: .
    ports:
      - 8000:8000
    command:
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_data:/static
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      -  postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    image: nginx:1.20-alpine
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  postgres_data:
  static_data:

