# Generated by Django 4.2 on 2023-04-11 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=150)),
                (
                    "main_page_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home/post_images/main_page_images",
                    ),
                ),
                (
                    "post_cover_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/post_images/post_covers"
                    ),
                ),
                ("post_size", models.IntegerField(default=0)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("postLatitude", models.FloatField(blank=True, null=True)),
                ("postLongitude", models.FloatField(blank=True, null=True)),
            ],
            options={"ordering": ["-updated"],},
        ),
        migrations.CreateModel(
            name="Traveler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/travelers_avatars"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/point_images/"
                    ),
                ),
                (
                    "post_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points",
                        to="home.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70)),
                ("text_block", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/article_images/"
                    ),
                ),
                (
                    "post_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="home.post",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="travelers",
            field=models.ManyToManyField(to="home.traveler"),
        ),
    ]
