# Generated by Django 4.2 on 2023-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Traveler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/travelers_avatars"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=150)),
                (
                    "main_page_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home/post_images/main_page_images",
                    ),
                ),
                (
                    "post_cover_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/post_images/post_covers"
                    ),
                ),
                ("post_size", models.IntegerField(default=0)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("coordinates", models.CharField(blank=True, max_length=50, null=True)),
                ("travelers", models.ManyToManyField(to="home.traveler")),
            ],
            options={"ordering": ["-updated"],},
        ),
    ]
