# Generated by Django 4.2 on 2023-04-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="coordinates",),
        migrations.AddField(
            model_name="post",
            name="postLatitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="postLongitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
