# Generated by Django 4.2 on 2023-04-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postarticle",
            name="img_location",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="postarticle",
            name="img_shape",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
