# Generated by Django 4.2 on 2023-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_postarticle_img_location_postarticle_img_shape"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_size",
            field=models.CharField(
                choices=[("Common", "Common"), ("Big", "Big")],
                default="Common",
                max_length=15,
            ),
        ),
    ]
