# Generated by Django 4.2 on 2023-04-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_post_coordinates_post_postlatitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/point_images/"
                    ),
                ),
                (
                    "post_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points",
                        to="home.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70)),
                ("text_block", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/article_images/"
                    ),
                ),
                (
                    "post_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="home.post",
                    ),
                ),
            ],
        ),
    ]
