# Generated by Django 4.2 on 2023-04-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_post_post_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="postarticle", name="img_location",),
        migrations.RemoveField(model_name="postarticle", name="img_shape",),
        migrations.AddField(
            model_name="postarticle",
            name="articleRatio",
            field=models.CharField(
                blank=True,
                choices=[("Horizontal", "Horizontal"), ("Vertical", "Vertical")],
                default="Horizontal",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="postarticle",
            name="imageSide",
            field=models.CharField(
                blank=True,
                choices=[("Left", "Left"), ("Right", "Right")],
                default="Left",
                null=True,
            ),
        ),
    ]
