# Generated by Django 4.2 on 2023-04-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_postarticle_img_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traveler",
            name="instagram",
            field=models.EmailField(
                blank=True,
                default="https://www.instagram.com/piotrpetya/",
                max_length=254,
                null=True,
            ),
        ),
    ]
