# Generated by Django 4.2 on 2023-04-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_traveler_instagram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveler",
            name="instagram",
            field=models.CharField(
                blank=True, default="https://www.instagram.com/piotrpetya/", null=True
            ),
        ),
    ]
