# Generated by Django 4.1.7 on 2023-04-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_travelers_remove_post_image_post_main_page_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='travelers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.travelers'),
        ),
    ]
