# Generated by Django 4.2 on 2023-04-08 22:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_traveler_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
