# Generated by Django 4.2 on 2023-04-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_post_post_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postarticle",
            name="articleRatio",
            field=models.CharField(
                blank=True,
                choices=[("H", "Horizontal"), ("V", "Vertical")],
                default="Horizontal",
                null=True,
            ),
        ),
    ]
