# Generated by Django 4.2 on 2023-04-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_postarticle"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="travelers",),
        migrations.AddField(
            model_name="post",
            name="travelers",
            field=models.ManyToManyField(blank=True, null=True, to="home.traveler"),
        ),
    ]
