# Generated by Django 4.2 on 2023-04-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_postarticle_articleratio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postarticle",
            name="articleRatio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("trip_block horizontal_foto_block", "Horizontal"),
                    ("trip_block vertical_foto_block", "Vertical"),
                ],
                default="Horizontal",
                null=True,
            ),
        ),
    ]
