# Generated by Django 4.2 on 2023-04-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_remove_post_travelers_post_travelers"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_cover_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="home/post_images/post_covers"
            ),
        ),
    ]
