# Generated by Django 4.2 on 2023-04-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_post_post_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postarticle',
            name='imageSide',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
