# Generated by Django 4.2 on 2023-04-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_post_post_cover_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
