# Generated by Django 4.2 on 2023-04-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_postarticle_imageside_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarticle',
            name='author',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
