# Generated by Django 4.2 on 2023-04-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_postarticle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postarticle',
            name='title',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
    ]
