# Generated by Django 4.2 on 2023-04-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_postarticle_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveler',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Пасты'},
        ),
    ]
