# Generated by Django 4.2 on 2023-04-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_traveler_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Пасты'},
        ),
        migrations.AlterModelOptions(
            name='postarticle',
            options={'verbose_name': 'Артыкул', 'verbose_name_plural': 'Артыклы'},
        ),
        migrations.AlterModelOptions(
            name='postpoint',
            options={'verbose_name': 'Наведанае месца', 'verbose_name_plural': 'Наведанае месцы'},
        ),
        migrations.AlterModelOptions(
            name='traveler',
            options={'verbose_name': 'Cябр', 'verbose_name_plural': 'Сябры'},
        ),
    ]
